{ ... }:
{
  imports = [
    ./aerospace.nix
    ./atuin.nix
    ./autojump.nix
    ./awscli.nix
    ./bat.nix
    ./editors/helix.nix
    ./editors/ideavim.nix
    ./editors/neovim.nix
    ./editors/vscode.nix
    ./editors/zed.nix
    ./eza.nix
    ./fzf.nix
    ./git.nix
    ./gpg.nix
    ./gtk.nix
    ./kde.nix
    ./shells/bash.nix
    ./shells/fish.nix
    ./shells/ion.nix
    ./shells/nushell.nix
    ./shells/powershell.nix
    ./shells/zsh.nix
    ./ssh.nix
    ./terminals/alacritty.nix
    ./terminals/ghostty.nix
    ./terminals/hyper.nix
    ./terminals/kitty.nix
    ./terminals/rio.nix
    ./terminals/wezterm.nix
    ./tmux.nix
    ./volta.nix
    ./zellij.nix
    ./zoxide.nix
  ];
}
