# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &personal_current age1txemjnq72tf7wx85a5klf8f72fgm3yll0pkpuuj79rwjfa4c8qtq9ww6u8
  - &personal_old age1wtjnrhlhdw28f88gakkewlju5edksrsl6ray4rw2z30vzunkvddqz75sck
  - &server_eros age1q9pv3enk7x3w7dxm55f4svqlhse9ztfcfwmsfc2eqcfclha34pls7vw2w2
  - &server_vnjtecmbcd age1jukfrhvgtf9w07p7gyulz4tc3ypudul0llvevl6k8p88ps7fsv6qqc8v5y
  - &server_nyx age1svkqsf5r7ykyw2wam85vecgkp7sy3e8ava8ajfamjnsxgcep9vgsep4292
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *personal_current
          - *personal_old
          - *server_eros
          - *server_vnjtecmbcd
          - *server_nyx
