#█▓▒░ fake x hax
#export DISPLAY=:0
(&>/dev/null ~/.local/bin/exorg &)

#█▓▒░ ssh & gpg keychain init
# eval $(keychain --dir "$XDG_RUNTIME_DIR"\
# 	--absolute -q --agents gpg \
# 	--eval ~/.ssh/id_ed25519 0x3834814930B83A30 0xBFEB75D960DFAA6B)

#█▓▒░ 1Password + secrets management
# Handled in interactive zsh init (see `~/.config/zsh/07-functions.zsh`).

